stages:
  - test
  - build
  - publish

cache:
  untracked: true

test:
  stage: test
  script:
    - npm install
    - npm run test
  tags:
    - NodeJS
    - NPM

build:
  stage: build
  script:
    - npm run build
    - npm run documentation
  only:
    - tags
  tags:
    - NodeJS
    - NPM
  artifacts:
    untracked: true
    paths:
      - ./distribution

publish:
  stage: publish
  only:
    - tags
  script:
    - npm publish ./distribution --access public
  tags:
    - NodeJS
    - NPM
  dependencies:
    - build
